
;---------------------
;
; Test the try{}catch(){} syntax. Thrown in a namespace for fun.
;
;----------------------


namespace some_name {

    nothing function(num some, string other, dict params) {
        ; a try block cannot be empty
        try {

            some_func(call_another(z, y, x))

            try {
                x = y
            }
            ; a try block must have at least one except block
            except {
                for(x in a_func(m)) {
                    do_something()
                }
            }
        }
        ; but the except block can be empty
        except(asdf.qwe) {}
        ; semantically, the except block wants an object of some kind.
        except(sdf.asd) {}
        except() {} ; blank expressions are true...
        ; uncomment this line for a syntax error
        ; except {}
    }
}

